In [5]:
cd /content/drive/My Drive/Lensing/mag/A370sum

/content/drive/My Drive/Lensing/mag/A370sum


In [ ]:
import sys
import numpy as np
import operator
from scipy import optimize

plummers = np.genfromtxt('invX_plummers.dat', dtype=(
    {'names': ['x', 'y', 'width', 'mass'], 'formats': ['f8', 'f8', 'f8', 'f8']}))

plumno = np.genfromtxt('plum_no.dat', dtype=(
    {'names': ['no'],'formats': ['i4']}))

mult = np.genfromtxt('images_combined_mult.dat', dtype=(
    {'names': ['no'],'formats': ['i4']}))

image = np.genfromtxt('images_combined.out', dtype=(
    {'names': ['tag', 'x', 'y', 'z'], 'formats': ['f8', 'f8', 'f8', 'f8']}))

In [ ]:
m= [0 for n in range(41)]
mass=np.zeros((40,2),dtype=(int,float))

m[0]=0
for i in range(40):
    m[i+1]=plumno['no'][i-1]+m[i]

    for j in range(m[i],m[i+1]):
        mass[i,0]=i+1
#         if plummers['y'][j]<-50 or plummers['y'][j]>50:
#         print(m[i],m[i+1])
        mass[i,1]+=plummers['mass'][j]
# mass=list(enumerate(mass))


In [16]:
from operator import itemgetter, attrgetter
sorted(mass, key=itemgetter(1),reverse=True)


[array([              27, 1135561723989111]),
 array([               8, 1129211184104880]),
 array([               4, 1109305443295458]),
 array([              25, 1109284401502163]),
 array([              17, 1074852930722075]),
 array([             35, 989841285350807]),
 array([             38, 978473987674309]),
 array([             23, 977795497311743]),
 array([             21, 975675479832641]),
 array([             19, 970172317182467]),
 array([              7, 966404232224239]),
 array([             28, 959474021976966]),
 array([              1, 957604733828318]),
 array([             32, 955923607697456]),
 array([             12, 953091167755110]),
 array([             31, 952677713213312]),
 array([             40, 952207898531910]),
 array([             13, 951892712709338]),
 array([             24, 942084151257483]),
 array([             14, 941652764327869]),
 array([             37, 941080451025738]),
 array([             20, 931706363537768]),
 array([             1

In [ ]:
import pandas as pd

In [10]:
s=pd.DataFrame(mass[:,:])
print(s.sort_values(by=1, ascending=False))
s.dtypes

     0                 1
26  27  1135561723989111
7    8  1129211184104880
3    4  1109305443295458
24  25  1109284401502163
16  17  1074852930722075
34  35   989841285350807
37  38   978473987674309
22  23   977795497311743
20  21   975675479832641
18  19   970172317182467
6    7   966404232224239
27  28   959474021976966
0    1   957604733828318
31  32   955923607697456
11  12   953091167755110
30  31   952677713213312
39  40   952207898531910
12  13   951892712709338
23  24   942084151257483
13  14   941652764327869
36  37   941080451025738
19  20   931706363537768
14  15   931228167738356
38  39   930629338911968
21  22   928640926468029
35  36   923249811569156
15  16   919696038609226
10  11   919086725830783
2    3   914403334985245
33  34   910896440651488
5    6   909609951483578
28  29   903419838294177
1    2   899752600871952
8    9   897001442676534
32  33   890361223527865
25  26   824633131796133
29  30   823434773273847
17  18   816527075064742
9   10   798981808274160


0    int64
1    int64
dtype: object

In [11]:
s=pd.DataFrame(mass[:,:])
print(s.sort_values(by=1, ascending=False))
s.dtypes

     0                 1
26  27  1135561723989111
7    8  1129211184104880
3    4  1109305443295458
24  25  1109284401502163
16  17  1074852930722075
34  35   989841285350807
37  38   978473987674309
22  23   977795497311743
20  21   975675479832641
18  19   970172317182467
6    7   966404232224239
27  28   959474021976966
0    1   957604733828318
31  32   955923607697456
11  12   953091167755110
30  31   952677713213312
39  40   952207898531910
12  13   951892712709338
23  24   942084151257483
13  14   941652764327869
36  37   941080451025738
19  20   931706363537768
14  15   931228167738356
38  39   930629338911968
21  22   928640926468029
35  36   923249811569156
15  16   919696038609226
10  11   919086725830783
2    3   914403334985245
33  34   910896440651488
5    6   909609951483578
28  29   903419838294177
1    2   899752600871952
8    9   897001442676534
32  33   890361223527865
25  26   824633131796133
29  30   823434773273847
17  18   816527075064742
9   10   798981808274160


0    int64
1    int64
dtype: object

In [12]:
print(mult['no'])

[3 5 3 3 4 3 5 2 3 2 3 3 3 5 5 3 3 3 2 3 3 3 2 2 3 3 3 2 2 2 2 2 3 3 3 2 2
 3 3]


In [13]:
px=plummers['x']
py=plummers['y']
pmass=plummers['mass']
pw=plummers['width']
print(pw)

[19.16896761 19.16896761 19.16896761 ...  4.88116967  9.76233934
  9.76233934]


In [ ]:
import seaborn as sns